remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Nancy's Story
description: The tale of a theme on gitHub pages!
show_downloads: false
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
